apiVersion: v1
kind: Service
metadata:
  name: mimir
  namespace: monitoring
spec:
  selector:
    app: mimir
  ports:
  - port: 9009
    targetPort: 9009
    name: http
  - port: 9097
    targetPort: 9097
    name: grpc
  - port: 7946
    targetPort: 7946
    name: memberlist
